apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations.actions.promoter.argoproj.io_PullRequest: |
    discovery.lua: |
      local actions = {}
      actions["merge"] = {["disabled"] = false}
      return actions
    definitions:
    - name: merge
      action.lua: |
        obj.spec.state = "merged"
        return obj
  resource.customizations.actions.promoter.argoproj.io_CommitStatus: |
    discovery.lua: |
      local actions = {}
      actions["hcap on"] = {["disabled"] = false}
      actions["hcap off"] = {["disabled"] = false}
      return actions
    definitions:
    - name: "hcapon"
      action.lua: |
        obj.metadata.annotations.hcapActive = "true"
        return obj
    - name: "hcapoff"
      action.lua: |
        obj.metadata.annotations.hcapActive = "false"
        return obj
